#!/usr/bin/env bash
#
# Emits the scalar variables the documentation templates read, as strict JSON on stdout.
#
# `Cargo.toml` is the single source of truth for the two versions the documentation quotes: the
# `terrace-config` tag the loader is pinned at, and the `csp-shell` tag the policy builder is.
# Both are moved by dependency updates, which is exactly when a hand-written README starts
# advertising a version this repository no longer builds against.
#
# The tables are not here - they are generated by `config-docs.sh` and injected as partials.
#
# Run it yourself to see what CI will render with:
#
#     bash .github/scripts/docs-variables.sh
#
# Deliberately POSIX tools only, no `jq`: it is not present in a default Git for Windows shell,
# and a script that only runs on the CI runner is a script nobody checks their edit against.
set -euo pipefail

manifest="${1:-Cargo.toml}"

# Reads the `tag = "…"` out of a workspace dependency's inline table, and rejects anything that
# would need JSON escaping. A tag is an alphabet the `printf` at the bottom can be trusted with,
# which is what keeps this free of a JSON encoder.
tag() {
    local crate="$1" value
    value="$(sed -n "s/^${crate} = {.*tag = \"\([^\"]*\)\".*/\1/p" "${manifest}" | head -n1)"

    if [ -z "${value}" ]; then
        echo "docs-variables: no git tag for '${crate}' in ${manifest}" >&2
        return 1
    fi

    if ! printf '%s' "${value}" | grep -Eq '^[0-9A-Za-z][0-9A-Za-z.+-]*$'; then
        echo "docs-variables: '${crate}' tag '${value}' is not a version tag" >&2
        return 1
    fi

    printf '%s' "${value}"
}

terrace_config="$(tag terrace-config)"
csp_shell="$(tag csp-shell)"

printf '{"terrace_config_tag":"%s","csp_shell_tag":"%s"}\n' "${terrace_config}" "${csp_shell}"
