[package]
name = "mp-stats-server"
version = "0.14.1"
edition.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
mp-stats-config = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
