name: Update Files

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  update-lock-file:
    name: Ensure Cargo Lock File is Up-to-Date
    environment: ci
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.auto-commit.outputs.changes_detected }}
    permissions:
      contents: write # to push build artifacts
      pull-requests: write # to comment on PRs
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Generate Bot Token
        id: generate_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.ACTIONS_MAINTENANCE_APP_ID }}
          private-key: ${{ secrets.ACTIONS_MAINTENANCE_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ steps.generate_token.outputs.token }}

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3

      - name: Sync Cargo.lock with Cargo.toml
        run: cargo fetch

      - name: Commit and Push if changed
        id: auto-commit
        uses: TimSchoenle/actions/actions/common/commit-changes@8f15b94f827ea2005c0e32cadc86bb50969633dd # actions-common-commit-changes-v1.1.4
        with:
          commit_message: 'build: update Cargo.lock'
          file_pattern: 'Cargo.lock'
          token: ${{ steps.generate_token.outputs.token }}

      - name: Comment on PR
        if: steps.auto-commit.outputs.changes_detected == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Cargo.lock has been updated to match Cargo.toml.'
            })